param(
    [string]$Manifest = (Join-Path $PSScriptRoot '../AvionicsUi/Assets/avionics-ui.manifest.json'),
    [string]$Out = (Join-Path $PSScriptRoot '../Avionics/AvIconTable.cs')
)
$ErrorActionPreference = 'Stop'
$json = Get-Content -Raw $Manifest | ConvertFrom-Json
$names = @($json.icons.PSObject.Properties | ForEach-Object { $_.Name })
function Pascal([string]$n) { (($n -split '-') | ForEach-Object { if ($_ -match '^\d') { $_ } else { $_.Substring(0,1).ToUpper() + $_.Substring(1) } }) -join '' }
$enum = ($names | ForEach-Object { "        $(Pascal $_)," }) -join "`r`n"
$chars = ($names | ForEach-Object { "            '\u$($json.icons.$_)'," }) -join "`r`n"
$tabler = ($names | ForEach-Object { "            `"$_`"," }) -join "`r`n"
@"
// <auto-generated> by tools/Generate-AvIconTable.ps1 from AvionicsUi/Assets/avionics-ui.manifest.json. Do not edit. </auto-generated>
namespace NOAvionics
{
    /// <summary>Chrome icons (Tabler, MIT). Every tab and section header carries one (spec section 5.4).</summary>
    public enum AvIcon
    {
        None = 0,
$enum
    }

    public static class AvIconTable
    {
        private static readonly char[] Chars =
        {
            '\0',
$chars
        };

        private static readonly string[] Names =
        {
            "",
$tabler
        };

        public static int Count => Chars.Length - 1;
        public static char Char(AvIcon icon) { int i = (int)icon; return i > 0 && i < Chars.Length ? Chars[i] : '\0'; }
        public static string TablerName(AvIcon icon) { int i = (int)icon; return i > 0 && i < Names.Length ? Names[i] : ""; }
    }
}
"@ | Set-Content -Encoding UTF8 $Out
Write-Host "AvIconTable: $($names.Count) icons -> $Out"
