# A1 mesh data exporter. Reads Satellite.mesh.json (Blender frame, applied transforms),
# merges parts per material, swaps to the Unity frame (x, z, y) with matching winding,
# and writes the runtime arrays as C#. Usage:
#   python ExportMeshData.py <source-dir> <out-cs>
import json
import sys

sourceDir = sys.argv[1]
outPath = sys.argv[2]

with open(sourceDir + "/Satellite.mesh.json") as handle:
    model = json.load(handle)
assert model["frame"] == "blender", "expected the Blender frame"

materials = ["Hull", "Panel"]
merged = {name: {"verts": [], "tris": []} for name in materials}
for part in model["parts"]:
    bucket = merged.get(part["material"])
    assert bucket is not None, "unexpected material " + part["material"]
    base = len(bucket["verts"])
    for v in part["verts"]:
        bucket["verts"].append((v[0], v[2], v[1]))
    for t in part["tris"]:
        bucket["tris"].append((base + t[0], base + t[2], base + t[1]))

totalTris = sum(len(bucket["tris"]) for bucket in merged.values())
assert totalTris <= 2000 // 3 * 3, "A1 blows the 2k tri budget"


def floats(values):
    return ", ".join(repr(c) + "f" for v in values for c in v)


def ints(values):
    return ", ".join(str(i) for t in values for i in t)


lines = []
lines.append("// <auto-generated> by modules/Support/Assets/Source/ExportMeshData.py")
lines.append("// from Satellite.mesh.json (A1 tasking satellite). Do not edit. </auto-generated>")
lines.append("namespace BoscaliSummer.Modules.Support.Visuals")
lines.append("{")
lines.append("    /// <summary>A1 tasking satellite mesh: Blender-authored bus, panels, struts and")
lines.append("    /// dish in the Unity frame, merged per material. Normals are recomputed at build.</summary>")
lines.append("    internal static class SatelliteMeshData")
lines.append("    {")
for name in materials:
    bucket = merged[name]
    lines.append("        public static readonly float[] %sVerts = { %s };" % (name, floats(bucket["verts"])))
    lines.append("        public static readonly int[] %sTris = { %s };" % (name, ints(bucket["tris"])))
lines.append("    }")
lines.append("}")
lines.append("")

with open(outPath, "w") as handle:
    handle.write("\n".join(lines))

print("A1 mesh data: %d tris -> %s" % (totalTris, outPath))
